# Generated by Django 4.0.5 on 2022-06-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='Cards/'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='Avatares/'),
        ),
    ]
