# Generated by Django 4.0.4 on 2022-06-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_App', '0002_alter_cards_imagen_alter_usuarios_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='categoria',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='links',
            field=models.IntegerField(null=True),
        ),
    ]
