# Generated by Django 4.0.5 on 2022-06-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_App', '0006_cards_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='cumpleaños',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='estado',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='perfil',
            field=models.TextField(null=True),
        ),
    ]
